development:
  adapter: postgresql
  encoding: unicode
  database: dl_development
  pool: 5
  username: ehamilton
  password:
  timeout: 5000
  
test:
  adapter: postgresql
  encoding: unicode
  database: dl_test
  pool: 5
  username: ehamilton
  password:
  timeout: 5000